root: true
extends:
  - airbnb-base
  - plugin:react/recommended
env:
  browser: true
plugins:
  - react
parserOptions:
  ecmaFeatures:
      jsx: true
globals:
  graphql: true
rules:
  no-console: 0
  no-nested-ternary: 0
  no-use-before-define: 0
  import/no-extraneous-dependencies: 0
  no-confusing-arrow: 0
  import/first: 0
  react/display-name: 0
  react/prop-types: 0
  max-len: [error, {code: 120}]
overrides:
  - files: gatsby-node.js
    rules:
      consistent-return: 0
      no-shadow: 0
