title: Hacking the Library
timezone: America/New_York
email: steele@osteele.com
description: 'Let’s create a new kind of Library.'

course:
  title: 'Special Topics in Computing: Hacking the Library'
  number: ENGR3599

collections:
  posts:
    title: Dailies
    output: true
    permalink: "/posts/:path/"
  pages:
    title: Pages
    output: true
    permalink: "/:path/"

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page

gems:
- jekyll-redirect-from

whitelist:
- jekyll-redirect-from

exclude:
- Gemfile
- Gemfile.lock
- README.md
- scripts
- vendor
