backend:
  name: github
  repo: olinlibrary/htl18.web

media_folder: src/pages/img
public_folder: /img

collections:
  - name: page
    label: Page
    folder: src/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }

  - name: assignment
    label: Assignment
    folder: src/pages/assignments
    create: true
    slug: "{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date, format: "YYYY-MM-DD" }
      - { name: body, label: Body, widget: markdown }

  - name: post
    label: Essay
    folder: src/pages/posts
    create: true
    slug: "{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: author, label: Author, widget: string }
      - { name: date, label: Date, widget: date, format: "YYYY-MM-DD" }
      - { name: description, label: Description, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }
