backend:
  name: github
  repo: olinlibrary/htl18.web

media_folder: static/assets
public_folder: /assets

collections:
  - name: page
    label: Page
    folder: src/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }
